main:
  - name: Home
    url: /
    weight: 10
  - name: Resume
    url: /about/
    weight: 20
  - name: Projects
    weight: 30
    hasChildren: true
  - parent: Projects
    name: LDPC Coding
    url: /project/recommendation/
    weight: 10
  - parent: Projects
    name: Mobile Network
    url: /project/cartoon/
    weight: 20
  - parent: Projects
    name: Network Slicing
    url: /project/cosmetics/
    weight: 30
  - name: Inform
    weight: 40  
    hasChildren: true
  - parent: Inform
    name: Notice
    url: /sns/notice/
  - parent: Inform 
    name: SNS
    url: /sns/
  - name: Certifications
    url: /license/
    weight: 50
  - name: Contact
    url: /map/
    weight: 60
