# Navigation Links
#   To link a homepage widget, specify the URL as a hash # followed by the filename of the
  #     desired widget in your content/home/ folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: 이력서
    weight: 20
    hasChildren: true
  - parent: 이력서
    name: 경력
    url: /resume/experience/
    weight: 10
  - parent: 이력서
    name: 학력
    url: /resume/education/
    weight: 20
  - name: 프로젝트
    weight: 30
    hasChildren: true
  - parent: 프로젝트
    name: LDPC coding
    url: /project/recommendation/
    weight: 10
  - parent: 프로젝트
    name: Computer Network
    url: /project/cartoon/
    weight: 20
  - parent: 프로젝트
    name: Network Slicing
    url: /project/cosmetics/
    weight: 30
  - name: SNS
    url: /sns/
    weight: 40   
  - name: 자격증 및 기술
    weight: 50
    hasChildren: true
  - parent: 자격증 및 기술
    name: 자격증
    url: /certifications/
  - parent: 자격증 및 기술  
    name: 기술
    url: /technologies/
  - name: 지도
    url: /map/
    weight: 60