# Navigation Links
#   To link a homepage widget, specify the URL as a hash # followed by the filename of the
  #     desired widget in your content/home/ folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: 이력서
    url: /about/
    weight: 20
  - name: 프로젝트
    weight: 30
    hasChildren: true
  - parent: 프로젝트
    name: LDPC coding
    url: /project/recommendation/
    weight: 10
  - parent: 프로젝트
    name: Mobile Network
    url: /project/cartoon/
    weight: 20
  - parent: 프로젝트
    name: Network Slicing
    url: /project/cosmetics/
    weight: 30
  - name: Inform
    weight: 40  
  - parent: Inform
    name: 공지
    url: /sns/notice/
    weight: 10
  - parent: Inform
    name: SNS
    url: /sns/
    weight: 20
  - name: 자격증
    url: /license/
    weight: 50
  - name: Contact
    url: /map/
    weight: 60