main:
  - name: Home
    url: /
    weight: 10
  - name: Resume
    url: /about/
    weight: 20
  - name: Project
    url: /pro/
    weight: 30
    hasChildren: true
  - name: SNS
    url: /sns/
    weight: 40
  - name: Certifications
    url: /license/
    weight: 50
  - name: Contact
    url: /map/
    weight: 60
